name = "ai-portfolio-builder"
main = "index.js"
compatibility_date = "2026-02-17"

account_id = "e506d2ef2602866c8b18942256a5b3b2"

workers_dev = true

[vars]
ENVIRONMENT = "production"
WORKER_VERSION = "1.1.0"
LOCK_FILE_VERSION = "1.1.0"

[observability]
enabled = true

[[kv_namespaces]]
binding = "PROMPT_CACHE"
id = "93fbd6d5157e427982298c6cbe8a05d4"

[env.production]
name = "ai-portfolio-builder"